---
- hosts: all
  vars:
    settings_secret_key: "{{ lookup('passowrd', playbook_dir + '/generated/secretkey chars=ascii_letters,digits,hexdigits,punctuation') }}"

  tasks:
    - name: checking if up or reload...
      stat: path=/home/vagrant/notinitial
      register: notinitial

    - name: creating flag directory if initial up...
      command: touch notinitial chdir=/home/vagrant/
      when: not notinitial.stat.exists

    - name: updating system packages...
      sudo: yes
      apt:
        cache_valid_time=86400
        update_cache=yes
        upgrade=safe
      ignore_errors: yes

    - name: Getting node source...
      get_url: url=https://deb.nodesource.com/setup_4.x dest=/home/vagrant/nodejs.sh

    - name: Change script permissions...
      file: path=/home/vagrant/nodejs.sh mode=0777

    - name: Execute node source...
      sudo: yes
      command: /bin/bash nodejs.sh chdir=/home/vagrant

    - name: installing virtualenv...
      sudo: yes
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - build-essential
        - libxml2-dev
        - libxslt1-dev
        - libjpeg-dev
        - python-dev
        - python-virtualenv
        - zlib1g-dev
        - nodejs

    - name: installing less...
      sudo: yes
      npm: name=less global=yes

    - name: installing git...
      sudo: yes
      apt: name=git-core update_cache=yes cache_valid_time=3600 state=present
      when: not notinitial.stat.exists

    - name: creating virtualenv...
      command: virtualenv {{ virtualenv_path }} -p python2.7 creates="{{ virtualenv_path }}"

      #TODO: Take this out when version is pinned in apps
    - name: installing correct version of django...
      pip: name=django version=1.4 state=present virtualenv={{ virtualenv_path }}
      when: not notinitial.stat.exists

    - name: installing apps from github...
      pip: name={{ item }} virtualenv={{ virtualenv_path }}
      ignore_errors: yes
      #when: not notinitial.stat.exists
      with_items:
        - "{{ git_eggs }}"

    - name: installing PEP8...
      pip: name=pep8 virtualenv={{ virtualenv_path }}
      when: not notinitial.stat.exists

    - name: checking if team-tools project was already created...
      stat: path=/vagrant/venv-tools/{{ project_name }}
      register: proj_created

    - name: creating project...
      command: "{{ virtualenv_path }}/bin/django-admin.py startproject {{ project_name }} chdir={{ virtualenv_path }}"
      when: not proj_created.stat.exists

    - name: copying over the urls.py to each app..
      sudo: yes
      template: src=templates/{{ item.0 }} dest={{ item.1 }}/urls.py
      with_together:
        - "{{ urls }}"
        - "{{ app_locations }}"

    - name: copying over the settings.py to each app...
      sudo: yes
      template: src=templates/{{ item.0 }} dest={{ item.1 }}/settings.py
      with_together:
        - "{{ settings }}"
        - "{{ app_locations }}"

    - name: syncing database...
      django_manage: command=syncdb app_path={{ virtualenv_path }}/{{ project_name }} virtualenv={{ virtualenv_path }}

    - name: migrating app database...
      django_manage: command=migrate app_path={{ virtualenv_path }}/{{ project_name }} virtualenv={{ virtualenv_path }}
